### ISSUE TITLE
make-recentlyupdated failing

### ISSUE THREAD

**Issue by benharri** [tildeclub/recently-updated#1]
json
```
ln: failed to access '/usr/share/nginx/html/tilde.24h.json.tmp': No such file or directory
rm: cannot remove '/usr/share/nginx/html/tilde.24h.json.tmp': No such file or directory
```

html
```
ln: failed to access '/usr/share/nginx/html/tilde.24h.php.tmp': No such file or directory
rm: cannot remove '/usr/share/nginx/html/tilde.24h.php.tmp': No such file or directory
```

**Comment by benharri** [comment]
I haven't worked on this version of recently-updated so I'm not 100% sure what's going on here

**Comment by deepend-tildeclub** [comment]
I can look into it.. For all I know I could have set it up wrong originally.   But will take a look and see what I can see :)  Thanks for reminding me about that. I remember getting an email regarding it but I've been busy/distracted lately :)
